const List<String> words = [
  'Pop-up',
  'Wi-Fi',
  'Lag',
  'Plug-in',
  'Click',
  'Scroll',
  'Swipe',
  'App Store',
  'Phone Call',
  'Text Message',
  'Refresh',
  'Upload',
  'Download',
  'Crash',
  'Browser',
  'Login',
  'Logout',
  'Password',
  'Error',
  'Charging',
  'Bluetooth',
  'Screenshot',
  'Emoji',
  'Wi-Fi Signal',
  'Mute',
  'Volume Up',
  'Volume Down',
  'Link',
  'Video Call',
  'Tablet',
  'Emoji Face',
  'Flash Drive',
  'Headphones',
  'Touch Screen',
  'Clickbait',
  'Data',
  'Video',
  'Mouse Click',
  'Touchpad',
  'Charging Cable',
  'Smartwatch',
  'Speaker',
  'Battery',
  'Notification',
  'Update',
  'System Settings',
  'Sync',
  'Camera',
  'Sound',
  'Game App',
  'Play Button',
  'Pause',
  'Reboot',
  'Bookmark',
  'Screenshot',
  'Search Bar',
  'Shortcut',
  'Icon',
  'Home Button',
  'Popup Ads',
  'Screen Brightness',
  'Volume Control',
  'Play Store',
  'Picture',
  'Text Alert',
  'Background App',
  'Phone Vibration',
  'Screenshot',
  'Touch Screen',
  'Call Waiting',
  'Game Controller',
  'Chat',
  'GIF',
  'QR Code',
  'Microphone',
  'Zoom In',
  'Zoom Out',
  'Reinstall',
  'Notification Bell',
  'Bluetooth Speaker',
  'App Update',
  'Smart Phone',
  'Emoji Keyboard',
  'Virtual Reality',
  'Smart Assistant',
  'Pop-up Menu',
  'Dark Mode',
  'Camera Lens',
  'Save File',
  'Refresh Button',
  'Virtual Keyboard',
  'Scroll Bar',
  'Screen Saver',
  'Slide Show',
  'Cursor',
  'Zoom Call',
  'Web Browser',
  'Downloading',
  'Uploading',
  'Virtual Button',
  'App Icon',
  'Smart Home',
  'App Crash',
  'App Notification',
  'Speaker Volume',
  'Control Panel',
  'Cloud Storage',
  'Voice Command',
  'Text to Speech',
  'Video Chat',
  'Photo Filter',
  'Software Update',
  'Audio File',
  'Video File',
  'GIF Maker',
  'Wireless',
  'Wireless Charger',
  'System Error',
  'Face Unlock',
  'Push Notification',
  'Memory Card',
  'Screen Lock',
  'Swipe Left',
  'Swipe Right',
  'Voice Message',
  'Play Music',
  'Record Video',
  'Play Game',
  'Smart TV',
  'Digital Assistant',
  'App Download',
  'App Launch',
  'Smart Fridge',
  'Remote Control',
  'File Transfer',
  'Settings Menu',
  'Hotspot',
  'Push Button',
  'Reset Button',
  'File Explorer',
  'App Icon',
  'Page Refresh',
  'Virtual Assistant',
  'Webpage',
  'Mobile Data',
  'Internet Browser',
  'System Settings',
  'Auto Play',
  'Auto Save'
];
